### ISSUE TITLE
secret key in config file?

### ISSUE THREAD

**Issue by alenros** [citruz/fakeartist#1]
I'm not familiar with Elixir, but in your config file (fakeartist/config/config.exs) there is a secret_key_base variable that I think should be secret.

**Comment by citruz** [comment]
The secret key in `config.exs` is only used when starting the server locally. In production it is overridden by `prod.secret.exs` which retrieves the key from an environment variable. In my case, Gigalixir takes care of generating that.
But thanks for taking the time to open an issue!

**Comment by alenros** [comment]
Happy to hear that!
I thought it might be so, but I thought it's better if I ask.
By the way, if you are planning on adding a word list, I'd be happy to share the one I use.

**Comment by citruz** [comment]
Haha, no way. I was just writing you a mail, asking for that 😄 
That would be really nice. I already have a wordlist but has like 10 entries because I was too lazy. In return, I can offer you to translate the list to german as well :)

**Comment by alenros** [comment]
You can find the one I use here:
https://github.com/alenros/fake-artist/blob/master/lib/words-en.js

I have also collected a bunch of other word lists, including one for Fake-Artist in German. I'll mail you those if you send me your mail.
