### ISSUE TITLE
Game leader leave bug

### ISSUE THREAD

**Issue by dcdourado** [citruz/fakeartist#5]
Hello there!

I was just checking the application and, after creating a lobby, the party leader can't leave the game. The modal pops, and after confirming the leave action, nothing happens.

I'm new to the language but would love to help you out! Can I give it a try?

**Comment by citruz** [comment]
You are right, leaving the game is only possible if a minimum numbers of players are still left. If the game has not been started yet, that number is 1. So in theory the lobby leader can leave if there is at least one other player (even though I just noticed that this crashes the game :D).
If the game has already been started, the minimum number is 2 (see const.ex).
This check is performed in`rules.ex` `remove_player_helper`. The result of `Rules.remove_player` is passed back to the original caller. However, in `play.ex`, there is no actual error handling except for hiding the modal (see line 372).
The behavior could be improved:
- If the game has not been started, the lobby leader leaves the game and there is no other player, delete the game completely
- If the game has been started and leaving is not possible either hide the button or show an error message

Feel free to submit improvements :)

**Comment by citruz** [comment]
I fixed the bug which crashed the game if the lobby leader leaves in be5bafa.
